#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

# Java application bugfixes
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'

# Startup programs
nitrogen --restore &
xset r rate 300 30 &
xrandr --output HDMI-0 --brightness 0.5
picom -b &
mpd &
xsetroot -cursor_name left_ptr &
setxkbmap -layout us -option ctrl:swapcaps &
dunst &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config bottom_padding 27
bspc config ignore_ewmh_focus true

bspc rule -a Signal state=floating desktop=^5
bspc rule -a Emacs state=tiled
bspc rule -a feh state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Pavucontrol state=floating
bspc rule -a '*:Custom_ncmpcpp' state=floating
bspc rule -a 'burp-StartBurp' state=floating
bspc rule -a 'ghidra-Ghidra' state=floating
bspc rule -a 'jetbrains-studio' state=floating
bspc rule -a 'Nitrogen' state=floating
