" Really modified configuration file for gVim...
"
" Original written for Debian GNU/Linux by W.Akkerman <wakkerma@debian.org>
" Some modifications by J.H.M. Dassen <jhm@cistron.nl>
" Possible further changes by dr Bogdan Pawlik
" Final tailoring by Gynvael Coldwind <gynvael@coldwind.pl>
"
" Stolen by Bourbon

set nocompatible
set guifont=Consolas:h16:cEASTEUROPE   " Windows 7 has this font
set nobackup
set ruler
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
source $VIMRUNTIME/colors/inkpot_gc.vim

behave mswin
set shiftwidth=2
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set incsearch		" Incremental search
set autowrite		" Automatically save before commands like :next and :ma

set fenc=utf8
set enc=utf8
 
inoremap <F2> <Esc>:w<CR> a
noremap <F2> :w<CR>i 
set tabstop=8
set number 
autocmd BufEnter *.c setlocal expandtab 

set nobackup
set nohlsearch
set expandtab 

map <F6> <Esc>:setlocal spell spelllang=pl_PL<CR>
map <F7> <Esc>:setlocal spell spelllang=en_US<CR>
map <F8> <Esc>:setlocal nospell<CR>

au BufNewFile,BufRead *.frag,*.vert,*.fp,*.vp,*.glsl setf glsl 

" Highlight colors
hi h1 guibg=#00ff00
hi h2 guibg=#ffff00
hi h3 guibg=#ff00ff
hi h4 guibg=#00ffff

hi ColorColumn guibg=#343461 ctermbg=darkgrey
autocmd bufreadpre *.c set colorcolumn=81
autocmd bufreadpre *.py set colorcolumn=81
autocmd bufreadpre *.cc set colorcolumn=81
autocmd bufreadpre *.cpp set colorcolumn=81
autocmd bufreadpre *.h set colorcolumn=81

autocmd bufreadpre *.c setlocal textwidth=80
autocmd bufreadpre *.py setlocal textwidth=80
autocmd bufreadpre *.cc setlocal textwidth=80
autocmd bufreadpre *.cpp setlocal textwidth=80
autocmd bufreadpre *.h setlocal textwidth=80

set columns=85
set belloff=all
